[project]
name = 'Decentralized-Public-Street-Cleaning-and-Maintenance-Services'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.pothole-repair]
path = 'contracts/pothole-repair.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
